version: 0.0
os: linux
files:
- source: ./gs-rest-service-0.1.0.jar
  destination: /tmp
hooks:
  BeforeInstall:
  AfterInstall:
  ApplicationStart:
    - location: scripts/run.sh
      runas: root
  ApplicationStop:
